name: Free Windows RDP

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Enable RDP + Admin User
        shell: powershell
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0 -Force
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop" -ErrorAction SilentlyContinue
          net user administrator /active:yes
          net user administrator "NyxPass2026!" /add

      - name: Setup Ngrok with Secret
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile ngrok.zip
          Expand-Archive -Path ngrok.zip -DestinationPath . -Force
          .\ngrok.exe config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          Start-Process -FilePath .\ngrok.exe -ArgumentList "tcp 3389" -NoNewWindow

      - name: Show Tunnel & Keep Alive
        shell: powershell
        run: |
          Start-Sleep -Seconds 15
          Write-Output "Check above steps for ngrok tcp address"
          while ($true) { Start-Sleep -Seconds 300 }
